FROM python:alpine3.18

COPY --from=golang:1.20-alpine /usr/local/go/ /usr/local/go/
 
ENV PATH="/usr/local/go/bin:${PATH}"

COPY . /app

WORKDIR /app

RUN apk update && apk add --no-cache curl

RUN go build

RUN pip install flask

RUN pip install flask-cors

CMD ["python", "frontend_server.py", "&", "python", "backend_server.py"]
